workflows:
  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: blueskyconpvtltd@gmail.com
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.luxusmontral
      vars:
        BUNDLE_ID: "com.luxusmontral"
        XCODE_WORKSPACE: "Montreal Luxe Resort.xcworkspace"
        XCODE_SCHEME: "Montreal Luxe Resort"
        APP_STORE_APPLE_ID: 6698888468
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install || echo "No Podfile found, skipping pod install."
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Obfuscate Swift code
        script: |
          find . -name "*.swift" -print0 | xargs -0 sed -i '' -e 's/\b(\w+)\b/$1_obf/g'
      - name: Build ipa for distribution
        script: |
          xcodebuild -workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" archive -archivePath "$CM_BUILD_DIR/build/ios/xcarchive/$XCODE_SCHEME.xcarchive" | tee xcodebuild.log
          xcodebuild -exportArchive -archivePath "$CM_BUILD_DIR/build/ios/xcarchive/$XCODE_SCHEME.xcarchive" -exportOptionsPlist ExportOptions.plist -exportPath "$CM_BUILD_DIR/build/ios/ipa" | tee -a xcodebuild.log
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - artyr241993@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Montreal Luxe Resort
        submit_to_app_store: true
        cancel_previous_submissions: true
        release_type: MANUAL
